[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "chaoxing"
version = "3.1.3"
description = "超星学习通/超星尔雅/泛雅超星全自动无人值守完成任务点"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13,<4.0"
dynamic = ["dependencies"]

[tool.setuptools]
py-modules = ["main"]
packages = ["api"]

[tool.setuptools.data-files]
"share/chaoxing" = ["config_template.ini", "resource/font_map_table.json"]

[project.scripts]
chaoxing = "main:main"

[tool.setuptools.dynamic]
dependencies = {file=["requirements.txt"]}
